name: meet_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.0
  table_calendar: ^3.1.0
  intl: ^0.19.0
  # url_launcher: ^6.2.5
  shared_preferences: ^2.2.2
  wakelock: ^0.6.2
  # shake: ^2.2.0
  dropdown_search: ^5.0.6
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
